ux_icons:
    default_icon_attributes:
        class: 'Icon'
        xmlns: 'https://www.w3.org/2000/svg'

    icon_sets:

        # FeatureBox icons
        feature:
            alias: 'lucide'
            # icon_attributes:
